### ISSUE TITLE
训练时，报错，似乎是程序没有考虑容错

### ISSUE THREAD

**Issue by houlimin** [calmisential/TensorFlow2.0_SSD#14]
Traceback (most recent call last):
  File "E:/TensorFlow2.0_SSD-master/train.py", line 70, in <module>
    train_step(batch_images=images, batch_labels=labels)
  File "E:/TensorFlow2.0_SSD-master/train.py", line 57, in train_step
    gt_boxes = gt.generate_gt_boxes()
  File "E:\TensorFlow2.0_SSD-master\core\ground_truth.py", line 136, in generate_gt_boxes
    gt_boxes = self.__label_positive_and_negative_predicted_boxes(valid_true_boxes, self.predict_boxes)
  File "E:\TensorFlow2.0_SSD-master\core\ground_truth.py", line 98, in __label_positive_and_negative_predicted_boxes
    box_true_class = box_true[..., -1]
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by calmisential** [comment]
I will rewrite the code in the last one or two weeks.

**Comment by queliyong** [comment]
Same error +1

**Comment by jiollos** [comment]
same error, I used the rewritten code, but It still have the same problem.

**Comment by calmiLovesAI** [comment]
I have completely rewritten the code, and now the program will not report an error.
