### ISSUE TITLE
After one epoch, there is a problem, and can't save the model.

### ISSUE THREAD

**Issue by jiollos** [calmisential/TensorFlow2.0_SSD#15]
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    ssd.save_weights(filepath=save_model_dir+"epoch-{}".format(epoch), save_format="tf")
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1167, in save_weights
    self._trackable_saver.save(filepath, session=session)
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1187, in save
    file_prefix=file_prefix_tensor, object_graph_tensor=object_graph_tensor)
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1127, in _save_cached_when_graph_building
    object_graph_tensor=object_graph_tensor)
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1095, in _gather_saveables
    feed_additions) = self._graph_view.serialize_object_graph()
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 381, in serialize_object_graph
    trackable_objects, path_to_root)
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 337, in _serialize_gathered_objects
    object_names[obj] = _object_prefix_from_path(path)
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 64, in _object_prefix_from_path
    for trackable in path_to_root))
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 64, in <genexpr>
    for trackable in path_to_root))
  File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 57, in _escape_local_name
    return (name.replace(_ESCAPE_CHAR, _ESCAPE_CHAR + _ESCAPE_CHAR)
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by sunxianpeng123** [comment]
我也是同样的问题

**Comment by lemonight** [comment]
> Traceback (most recent call last):
> File "train.py", line 86, in
> ssd.save_weights(filepath=save_model_dir+"epoch-{}".format(epoch), save_format="tf")
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1167, in save_weights
> self._trackable_saver.save(filepath, session=session)
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1187, in save
> file_prefix=file_prefix_tensor, object_graph_tensor=object_graph_tensor)
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1127, in _save_cached_when_graph_building
> object_graph_tensor=object_graph_tensor)
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1095, in _gather_saveables
> feed_additions) = self._graph_view.serialize_object_graph()
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 381, in serialize_object_graph
> trackable_objects, path_to_root)
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 337, in _serialize_gathered_objects
> object_names[obj] = _object_prefix_from_path(path)
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 64, in _object_prefix_from_path
> for trackable in path_to_root))
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 64, in
> for trackable in path_to_root))
> File "C:\Users\jeo13\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 57, in _escape_local_name
> return (name.replace(_ESCAPE_CHAR, _ESCAPE_CHAR + _ESCAPE_CHAR)
> AttributeError: 'NoneType' object has no attribute 'replace'

你的数据里是不是没有标签的图

**Comment by raduciou** [comment]
that's my first comment on github so:
you need to put name of weights in order to save model (keras bug)
`self.add_weight(shape=(1, 1, 1, 512), dtype=tf.float32, initializer=tf.keras.initializers.Ones(), trainable=True, name='fckr')`

after this you can save it

**Comment by jianhaifeng** [comment]
the name in the file of ssd.py(line numer:13),like this: "self.learnable_factor = self.add_weight(shape=(1, 1, 1, 512), dtype=tf.float32, initializer=tf.keras.initializers.Ones(), trainable=True,name='ssd_train')"
